redis:
  host: localhost
  port: 6379

# Base log directory for Moira API and Moira Checker microservices
worker:
  log_dir: /var/log/moira/worker

api:
  port: 8081
  listen: '127.0.0.1'

# Moira microservices will send their own metrics to this address
graphite:
  uri: graphite-relay:2003
  prefix: DevOps.moira
  interval: 30

checker:
  # every trigger will be periodically checked even if no metrics arrive
  nodata_check_interval: 60 # (in seconds)
  # every trigger will be checked at most once every interval
  check_interval: 5 # (in seconds)
  # metrics older than this age will be purged after use
  metrics_ttl: 3600 # (in seconds)
  # if master is not receiving any metrics it stops nodata checks after that interval
  stop_checking_interval: 30 # (in seconds)

# Moira frontend uri, used to make links in notification templates
front:
  uri: http://localhost

notifier:
  log_file: /var/log/moira/notifier/notifier.log
  log_level: debug
  log_color: true
  sender_timeout: 10s0ms
  resending_timeout: 24:00 # 24 hours
  senders:
    - type: mail
      smtp_host: smtp.example.com
      smtp_port: 25
      from: moira@example.com
      insecure_tls: false
      # Authentication params (username, password, hostname)
      username:
      password:
      hostname:
    - type: slack
      api_token: # place your token here
    - type: pushover
      api_token: # place your token here
    - type: script
      name: MyCustomScript
      exec: /bin/bash /opt/myscripts/gsm-modem.sh
    - type: twilio sms
      api_asid: # place your api sid
      api_authtoken: # place your api secret
      api_fromphone: # place phone
    - type: twilio voice
      api_asid: # place your api sid
      api_authtoken: # place your api secret
      api_fromphone: # place phone
      voiceurl: # place your voice url


cache:
  log_file: /var/log/moira/cache/cache.log
  listen: ':2003' # listen on all interfaces
  retention-config: /etc/moira/cache/storage-schemas.conf
  pid: /var/run/moira-cache.pid
