name: Publish spec version to SwaggerHub

on:
  push:
    branches:
      - master
      - v[0-9]+.[0-9]+.[0-9]+
      - feature/*

jobs:
  mergespec:
    name: Bundle spec files and validate it.
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: openapi

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: npm install -g swagger-cli
      - run: make spec

      - name: Save build artifact
        uses: actions/upload-artifact@v1
        with:
          name: specfile
          path: openapi/build/openapi.yml
    
  publishspec:
    name: Upload generated OpenAPI description
    runs-on: ubuntu-latest
    needs: mergespec
    defaults:
      run:
        working-directory: openapi

    steps:
      - uses: actions/checkout@v2
      - name: set output for versioning
        id: vars
        run: echo ::set-output name=tag::"${GITHUB_REF#refs/*/}"

      - run: mkdir build/
      - name: Download spec file artifact
        uses: actions/download-artifact@v1
        with:
          name: specfile
          path: openapi/build

      - name: Upload spec file to swaggerhub
        env:
          AUTH_TOKEN: ${{secrets.SWAGGERHUB_TOKEN}}
          BRANCH_NAME: ${{steps.vars.outputs.tag}}
          SWAGGERHUB_URL: "https://api.swaggerhub.com/apis/Moira/moira-alert"
        shell: bash
        run: |
          VERSION=`echo ${BRANCH_NAME}|sed 's#[^a-zA-Z0-9_\.\-]#_#g'`
          DEFINITION=`cat ./build/openapi.yml`
          curl -d "$DEFINITION" "${SWAGGERHUB_URL}/?isPrivate=false&version=${VERSION}&oas=3.0.0&force=true" -H "content-type: application/yaml" -H "Authorization: ${AUTH_TOKEN}"
