name: Publish spec version to SwaggerHub

on:
  push:
    branches:
      - master
      - v[0-9]+.[0-9]+.[0-9]+
      - feature/*

jobs:
  mergespec:
    name: Bundle spec files and validate it.
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: openapi

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "16"
      - run: npm install -g swagger-cli @openapitools/openapi-generator-cli
      - run: make spec
      - run: make validate-spec

      - name: Save build artifact
        uses: actions/upload-artifact@v1
        with:
          name: specfile
          path: openapi/build/openapi.yml
          
  #testspec:
  #  name: Test generated spec against the Moira API
  #  runs-on: ubuntu-latest
  #  needs: mergespec
  #  strategy:
  #    matrix:
  #      python-version: [3.8]

  #  steps:
  #    - uses: actions/checkout@v2
  #      with:
  #        repository: moira-alert/docker-compose
  #    - name: Set up docker services
  #      run: docker-compose up -d

      # Checkout again to switch back to `doc` repository
  #    - uses: actions/checkout@v2

  #    - name: Download spec file artifact
  #      uses: actions/download-artifact@v1
  #      with:
  #        name: specfile
  #        path: openapi/build

  #    - name: Set up Python ${{ matrix.python-version }}
  #      uses: actions/setup-python@v2
  #      with:
  #        python-version: ${{ matrix.python-version }}

  #    - name: Install schemathesis and run tests
  #      run: |
  #        python -m pip install --upgrade pip
  #        pip install schemathesis
  #        cd openapi
  #        make test-spec

  publishspec:
    name: Upload generated OpenAPI description
    runs-on: ubuntu-22.04
  # needs: testspec
    defaults:
      run:
        working-directory: openapi

    steps:
      - uses: actions/checkout@v2

    #  - name: Extract branch name on push
    #    if: github.event_name != 'pull_request'
    #    run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/})"

      - run: mkdir build/
      - name: Download spec file artifact
        uses: actions/download-artifact@v1
        with:
          name: specfile
          path: openapi/build

      - name: Upload spec file to swaggerhub
        env:
          AUTH_TOKEN: ${{secrets.SWAGGERHUB_TOKEN}}
          SWAGGERHUB_URL: "https://api.swaggerhub.com/apis/Moira/moira-alert"
        shell: bash
        run: |
          VERSION=`echo ${GITHUB_REF_NAME}| sed 's#[^a-zA-Z0-9_\.\-]#_#g'`
          DEFINITION=`cat ./build/openapi.yml`
          curl -d "$DEFINITION" "${SWAGGERHUB_URL}/?isPrivate=false&version=${VERSION}&oas=3.0.0&force=true" -H "content-type: application/yaml" -H "Authorization: ${AUTH_TOKEN}"
